language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - jruby
  - jruby-9.0.0.0.pre1
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
